# Generated by Django 5.0 on 2024-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('NO_CLASS', 'No Class Selected'), ('BCA1A', 'BCA I Year (Section A)'), ('BCA1B', 'BCA I Year (Section B)'), ('BCA2', 'BCA II Year'), ('BCA3', 'BCA Final Year'), ('BSC1', 'BSC I Year'), ('BSC2', 'BSC II Year'), ('BSC3', 'BSC Final Year'), ('MSC1', 'MSC I Year'), ('MSC2', 'MSC Final Year')], max_length=30),
        ),
    ]
