# Generated by Django 5.0 on 2024-01-31 18:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blacklisted", "0001_initial"),
        ("profiles", "0002_alter_student_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklistedstudent",
            name="blacklist_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="blacklistedstudent",
            name="reason",
            field=models.CharField(
                choices=[
                    ("NOT_PRESENT", "Not present in class"),
                    ("PROXY", "Marked proxy attendance"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="blacklistedstudent",
            name="teacher",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="blacklistedstudent",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.student",
            ),
        ),
    ]
