# Generated by Django 5.0 on 2024-01-31 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklisted', '0001_initial'),
        ('profiles', '0002_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedstudent',
            name='reason',
            field=models.CharField(choices=[('NOT_PRESENT', 'Not present in class'), ('PROXY', 'Marked proxy attendance')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklistedstudent',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.teacher'),
        ),
    ]
