# Generated by Django 5.0 on 2024-01-31 16:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklisted', '0002_blacklistedstudent_reason_blacklistedstudent_teacher'),
        ('profiles', '0002_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedstudent',
            name='blacklist_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='blacklistedstudent',
            name='reason',
            field=models.CharField(choices=[('NOT_PRESENT', 'Not present in class'), ('PROXY', 'Marked proxy attendance')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='blacklistedstudent',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.student'),
        ),
        migrations.AlterField(
            model_name='blacklistedstudent',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.teacher'),
        ),
    ]
