# Generated by Django 5.0 on 2023-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ads_url', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
