# Generated by Django 5.0 on 2024-10-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ads_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
