# Generated by Django 5.0 on 2023-12-07 12:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_date', models.DateField(default=datetime.date.today)),
                ('subject_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('unique_code', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ManyToManyField(to='profiles.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
