# Generated by Django 5.0 on 2024-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_class_name_alter_entry_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_slot',
            field=models.ManyToManyField(to='attendance.timeslot'),
        ),
    ]
