# Generated by Django 5.0 on 2025-07-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
